# Generated by Django 4.0.2 on 2022-02-14 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'oo',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=60, unique=True)),
                ('telegram_id', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'owners',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Pn_query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField()),
                ('text', models.TextField()),
                ('photo_link', models.FilePathField(blank=True, max_length=160, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_end', models.DateTimeField()),
                ('comment', models.TextField()),
                ('id_oo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pn_queries.oo')),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pn_queries.owner')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pn_queries.service')),
            ],
            options={
                'db_table': 'pn_queries',
            },
        ),
    ]
