# Generated by Django 4.0.2 on 2022-02-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pn_queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
