# Generated by Django 4.0.2 on 2022-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pn_queries', '0002_alter_owner_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pn_query',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pn_query',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
